server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #微信appId
    appId: wx7dca3ec8870281e1
    #微信appSecret
    appSecret: e5e1efdab8a6c9bcc43eeaf24b3b4141
    token: eureka
    #配置一个文字的模板ID
    singleTemplateId: Jnt8rhv102q5DPoK-Jxe7Uvew0NCfHuW0Jq1LFf370k
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: Jnt8rhv102q5DPoK-Jxe7Uvew0NCfHuW0Jq1LFf370k
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
#          - oK0U562Y5ijqYRpGUtNRs0vxxxWU
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 早上好呀呀鸭
            #你们的相遇时间
            meetDate: '1996-06-18'
            city: 成都
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 510107
            constellation: chunvzuo
          #用户openID，多用户可以按照格式继续添加下去
          填写你的需要特定配置的微信用户号:
            title: 早上好呀呀鸭
            meetDate: '2021-08-11'
            city: 肇庆
            cityCode: 440600
            constellation: 狮子座
      #颜文字模板
      emoticonsTemplate:
        templateId: 6Xv33iIBtsM9wF2rG31F5_S7jsDZsnuRKrm08RonJQo
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 天秤座

lbs:
  key: cd4de71007d59924ee713a70ef9adf5f

constellation:
  key: 填写星座接口key
